### ISSUE TITLE
Telegram Desktop read icon hard to read

### ISSUE THREAD

**Issue by orschiro** [xvitaly/tgbuild#10]
Hey @xvitaly 

Thanks for providing the RPM fusion package! Really nice.

However, can we maybe replace the current icon with the default one?

I find the current very hard to see if all messages are marked read.

The Telegram Desktop flatpak ships the default one.

See the following for a comparison:

![image](https://user-images.githubusercontent.com/170947/36165750-dba8f216-10f0-11e8-9791-a2892a560791.png)

**Comment by xvitaly** [comment]
> However, can we maybe replace the current icon with the default one?

We use official Telegram Desktop icon from it's repository:
![tdesktop](https://github.com/telegramdesktop/tdesktop/raw/dev/Telegram/Resources/art/icon256.png)

**Comment by xvitaly** [comment]
> Hmm thank you! Maybe I have this issue because I experimented with hardcode-tray when I had installed Linux Mint (now using the same home folder).

Also some GTK/KDE themes can change default icons for applications.

**Comment by orschiro** [comment]
Sorry @xvitaly for creating noise. The issue was due to not having reverted hardcode tray fixer:

https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/499#issuecomment-365555363
